create table
  public.league_admins (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    admin_userid uuid not null,
    constraint league_admins_pkey primary key (id),
    constraint league_admins_admin_userid_key unique (admin_userid),
    constraint league_admins_admin_userid_fkey foreign key (admin_userid) references auth.users (id) on update cascade
  ) tablespace pg_default;