
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."match_status" AS ENUM (
    'Upcoming',
    'Completed',
    'Cancelled'
);

ALTER TYPE "public"."match_status" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."characters" (
    "character_id" integer NOT NULL,
    "character_name" character varying(255) NOT NULL
);

ALTER TABLE "public"."characters" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."characters_character_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."characters_character_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."characters_character_id_seq" OWNED BY "public"."characters"."character_id";

CREATE TABLE IF NOT EXISTS "public"."configuration" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "configurationKey" character varying,
    "configurationValue" character varying
);

ALTER TABLE "public"."configuration" OWNER TO "postgres";

ALTER TABLE "public"."configuration" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."configuration_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."league_sign_ups" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "league_id" bigint,
    "discord_name" "text",
    "avatar_url" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL
);

ALTER TABLE "public"."league_sign_ups" OWNER TO "postgres";

ALTER TABLE "public"."league_sign_ups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."league_sign_ups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."leagues" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "league_name" character varying,
    "league_start_date" "date",
    "league_end_date" "date"
);

ALTER TABLE "public"."leagues" OWNER TO "postgres";

ALTER TABLE "public"."leagues" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."leagues_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."matchdetails" (
    "detail_id" integer NOT NULL,
    "match_id" integer,
    "player1_character_id" integer,
    "player2_character_id" integer,
    "player1_score" integer DEFAULT 0,
    "player2_score" integer DEFAULT 0,
    "replay_id" character varying(255) NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."matchdetails" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."matchdetails_detail_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."matchdetails_detail_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."matchdetails_detail_id_seq" OWNED BY "public"."matchdetails"."detail_id";

CREATE TABLE IF NOT EXISTS "public"."matches" (
    "match_id" integer NOT NULL,
    "player1_id" integer,
    "player2_id" integer,
    "scheduled_time" timestamp without time zone NOT NULL,
    "status" "public"."match_status" DEFAULT 'Upcoming'::"public"."match_status" NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."matches" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."matches_match_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."matches_match_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."matches_match_id_seq" OWNED BY "public"."matches"."match_id";

CREATE TABLE IF NOT EXISTS "public"."users" (
    "user_id" integer NOT NULL,
    "username" character varying(255) NOT NULL,
    "email" character varying(255) NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "public"."users" OWNER TO "postgres";

CREATE SEQUENCE IF NOT EXISTS "public"."users_user_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE "public"."users_user_id_seq" OWNER TO "postgres";

ALTER SEQUENCE "public"."users_user_id_seq" OWNED BY "public"."users"."user_id";

ALTER TABLE ONLY "public"."characters" ALTER COLUMN "character_id" SET DEFAULT "nextval"('"public"."characters_character_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."matchdetails" ALTER COLUMN "detail_id" SET DEFAULT "nextval"('"public"."matchdetails_detail_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."matches" ALTER COLUMN "match_id" SET DEFAULT "nextval"('"public"."matches_match_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."users" ALTER COLUMN "user_id" SET DEFAULT "nextval"('"public"."users_user_id_seq"'::"regclass");

ALTER TABLE ONLY "public"."characters"
    ADD CONSTRAINT "characters_character_name_key" UNIQUE ("character_name");

ALTER TABLE ONLY "public"."characters"
    ADD CONSTRAINT "characters_pkey" PRIMARY KEY ("character_id");

ALTER TABLE ONLY "public"."configuration"
    ADD CONSTRAINT "configuration_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."league_sign_ups"
    ADD CONSTRAINT "league_sign_ups_discord_name_key" UNIQUE ("discord_name");

ALTER TABLE ONLY "public"."league_sign_ups"
    ADD CONSTRAINT "league_sign_ups_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."league_sign_ups"
    ADD CONSTRAINT "league_sign_ups_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."leagues"
    ADD CONSTRAINT "leagues_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."matchdetails"
    ADD CONSTRAINT "matchdetails_pkey" PRIMARY KEY ("detail_id");

ALTER TABLE ONLY "public"."matchdetails"
    ADD CONSTRAINT "matchdetails_replay_id_key" UNIQUE ("replay_id");

ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_pkey" PRIMARY KEY ("match_id");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_id");

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");

ALTER TABLE ONLY "public"."league_sign_ups"
    ADD CONSTRAINT "league_sign_ups_league_id_fkey" FOREIGN KEY ("league_id") REFERENCES "public"."leagues"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."matchdetails"
    ADD CONSTRAINT "matchdetails_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("match_id");

ALTER TABLE ONLY "public"."matchdetails"
    ADD CONSTRAINT "matchdetails_player1_character_id_fkey" FOREIGN KEY ("player1_character_id") REFERENCES "public"."characters"("character_id");

ALTER TABLE ONLY "public"."matchdetails"
    ADD CONSTRAINT "matchdetails_player2_character_id_fkey" FOREIGN KEY ("player2_character_id") REFERENCES "public"."characters"("character_id");

ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_player1_id_fkey" FOREIGN KEY ("player1_id") REFERENCES "public"."users"("user_id");

ALTER TABLE ONLY "public"."matches"
    ADD CONSTRAINT "matches_player2_id_fkey" FOREIGN KEY ("player2_id") REFERENCES "public"."users"("user_id");

CREATE POLICY "Allow user to delete himself from the league" ON "public"."league_sign_ups" FOR DELETE USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Allow user to sign himself up" ON "public"."league_sign_ups" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable read access for all users" ON "public"."configuration" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."league_sign_ups" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."leagues" FOR SELECT USING (true);

ALTER TABLE "public"."characters" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."configuration" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."league_sign_ups" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."leagues" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."matchdetails" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."matches" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."characters" TO "anon";
GRANT ALL ON TABLE "public"."characters" TO "authenticated";
GRANT ALL ON TABLE "public"."characters" TO "service_role";

GRANT ALL ON SEQUENCE "public"."characters_character_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."characters_character_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."characters_character_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."configuration" TO "anon";
GRANT ALL ON TABLE "public"."configuration" TO "authenticated";
GRANT ALL ON TABLE "public"."configuration" TO "service_role";

GRANT ALL ON SEQUENCE "public"."configuration_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."configuration_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."configuration_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."league_sign_ups" TO "anon";
GRANT ALL ON TABLE "public"."league_sign_ups" TO "authenticated";
GRANT ALL ON TABLE "public"."league_sign_ups" TO "service_role";

GRANT ALL ON SEQUENCE "public"."league_sign_ups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."league_sign_ups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."league_sign_ups_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."leagues" TO "anon";
GRANT ALL ON TABLE "public"."leagues" TO "authenticated";
GRANT ALL ON TABLE "public"."leagues" TO "service_role";

GRANT ALL ON SEQUENCE "public"."leagues_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."leagues_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."leagues_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."matchdetails" TO "anon";
GRANT ALL ON TABLE "public"."matchdetails" TO "authenticated";
GRANT ALL ON TABLE "public"."matchdetails" TO "service_role";

GRANT ALL ON SEQUENCE "public"."matchdetails_detail_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."matchdetails_detail_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."matchdetails_detail_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."matches" TO "anon";
GRANT ALL ON TABLE "public"."matches" TO "authenticated";
GRANT ALL ON TABLE "public"."matches" TO "service_role";

GRANT ALL ON SEQUENCE "public"."matches_match_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."matches_match_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."matches_match_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";

GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
