create table "public"."league_matches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "league_id" bigint,
    "player1_discordid" uuid,
    "player2_discordid" uuid,
    "player1_score" integer not null default 0,
    "player2_score" integer not null default 0,
    "replay_ids" text,
    "match_status" match_status not null
);


alter table "public"."league_matches" enable row level security;

CREATE UNIQUE INDEX league_matches_pkey ON public.league_matches USING btree (id);

alter table "public"."league_matches" add constraint "league_matches_pkey" PRIMARY KEY using index "league_matches_pkey";

alter table "public"."league_matches" add constraint "league_matches_league_id_fkey" FOREIGN KEY (league_id) REFERENCES leagues(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."league_matches" validate constraint "league_matches_league_id_fkey";

alter table "public"."league_matches" add constraint "league_matches_player1_discordid_fkey" FOREIGN KEY (player1_discordid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."league_matches" validate constraint "league_matches_player1_discordid_fkey";

alter table "public"."league_matches" add constraint "league_matches_player2_discordid_fkey" FOREIGN KEY (player2_discordid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."league_matches" validate constraint "league_matches_player2_discordid_fkey";

grant delete on table "public"."league_matches" to "anon";

grant insert on table "public"."league_matches" to "anon";

grant references on table "public"."league_matches" to "anon";

grant select on table "public"."league_matches" to "anon";

grant trigger on table "public"."league_matches" to "anon";

grant truncate on table "public"."league_matches" to "anon";

grant update on table "public"."league_matches" to "anon";

grant delete on table "public"."league_matches" to "authenticated";

grant insert on table "public"."league_matches" to "authenticated";

grant references on table "public"."league_matches" to "authenticated";

grant select on table "public"."league_matches" to "authenticated";

grant trigger on table "public"."league_matches" to "authenticated";

grant truncate on table "public"."league_matches" to "authenticated";

grant update on table "public"."league_matches" to "authenticated";

grant delete on table "public"."league_matches" to "service_role";

grant insert on table "public"."league_matches" to "service_role";

grant references on table "public"."league_matches" to "service_role";

grant select on table "public"."league_matches" to "service_role";

grant trigger on table "public"."league_matches" to "service_role";

grant truncate on table "public"."league_matches" to "service_role";

grant update on table "public"."league_matches" to "service_role";